### ISSUE TITLE
I would like to help on contributing

### ISSUE THREAD

**Issue by hueitan** [javascriptmy/2015-may-meetup#1]
I would like to help on contributing as a Javascript Developer.

**Comment by matiassingers** [comment]
That's awesome @huei90!

Allow us a couple f days to properly get the initial website setup, and then everybody can easily improve upon it.

Have you checked out [our event](https://www.facebook.com/events/453348188153551/) in May yet?

**Comment by hueitan** [comment]
@matiassingers Yup.

I'm not able to attend the event because I'm not in Malaysia on that period.

**Comment by matiassingers** [comment]
@huei90 ah I see, that's too bad - hopefully you can make it for the next one :wink: 

Check out this repo for the website: https://github.com/javascriptmy/website

I'll open an issue about the website design later tonight, would love some feedback

**Comment by hueitan** [comment]
Got it!!
